title: Punggol View Primary School
url: https://punggolviewpri.moe.edu.sg
favicon: /images/School_Logo__high_res__1000x920_copy__PNG_.png
colors:
  primary-color: "#0f00ce"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Punggol View Primary School
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dlepvymbvefa4.amplifyapp.com/
prod: https://master.dlepvymbvefa4.amplifyapp.com/
shareicon: /images/School_Logo__high_res__1000x920_copy__PNG_.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
